spring:
  datasource:
    url: jdbc:postgresql://localhost:5322/epambambam
    username: postgres
    password: Dota2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true