spring:
  datasource:
    url: jdbc:postgresql://localhost:6322/stg-gym
    username: postgres
    password: barabulka
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true